remove hack based on runnumber=0
dmwm/CRABServer pull request #7574
Opened 2023-03-27 15:45 UTC by belforte

2023-03-27 18:03 UTC, novicecpp requested changes

2023-03-27 18:03 UTC, novicecpp commented on src/python/TaskWorker/Actions/DBSDataDiscovery.py
> -        runRange = kwargs['task']['tm_split_args']['runs']
Do not delete `runRange`. It is needed for [line 480](https://github.com/dmwm/CRABServer/blob/5bd657afce5387c95bfe830285fbda01cfc88e48/src/python/TaskWorker/Actions/DBSDataDiscovery.py#L480).

2023-03-27 18:03 UTC, novicecpp commented
Weird. I think I already reviewed this and you already merged it to master sometimes ago.
@belforte Did you really create PR today or it is reappear because something wrong with GitHub (GitHub server had some issues around lunch today)?

2023-03-27 21:22 UTC, belforte commented
yes it is very strange. I also remember having done this already and was surprised to see old code still there. I guess I messed up in some PR based on stale branch :-(

2023-03-28 10:36 UTC, novicecpp approved these changes
LGTM

2023-03-28 15:08 UTC, merged

2023-03-29 22:45 UTC, belforte commented
indeed there was already a reviewed PR for same topic. Which I had forgotten
Will now close https://github.com/dmwm/CRABServer/pull/7551