RUCIO_Transfers.py: Get info from first job but use info of file need publish if exists
dmwm/CRABServer pull request #7775
Opened 2023-07-18 17:42 UTC by novicecpp

Fix https://github.com/dmwm/CRABServer/issues/7741

2023-07-18 18:03 UTC, novicecpp commented
I need to test it before ask Stefano to review.

2023-07-19 15:53 UTC, belforte commented
I believe this will work, but hesitate to say "fine" since it looks quite intricated.
Besides what I wrote in comment to the code, I am puzzled that we need another flag.
In Rucio ASO, all files requires transfer, and whether a file should be published or not (i.e. EDM or not) is already part of the file info. Could we simply rely on `outputdatasets.startswith('/FakeDataset` ?

I am trying hard to understand how things work so to get convinced that we can simply set `publish=1` in `transfers.txt. It may requires an "if using Rucio" in the PostJob, but may make things much more readable.

My problem is the usual one, PostJob logic is intricated and I fail to have it clearly in mind while I look at other things.  But this is one reason more to keep `delayed_publicationflag_update` as an internal variable to PostJob.

I know that I approved the original idea of using  `delayed_publicationflag_update` but can not managed to feel good about this.

It is also true that life must go on, so if we do not converge quickly on a better idea, wll have to go for `delayed_publicationflag_update` but should at least add some explanation as comments in the code !

2023-07-19 15:54 UTC, belforte requested changes
see comment. Please think about it a bit. If you decide to keep it like this. Fine.

2023-07-20 05:29 UTC, novicecpp commented
> I believe this will work, but hesitate to say "fine" since it looks quite intricated. Besides what I wrote in comment to the code, I am puzzled that we need another flag. In Rucio ASO, all files requires transfer, and whether a file should be published or not (i.e. EDM or not) is already part of the file info. Could we simply rely on `outputdatasets.startswith('/FakeDataset` ?

We can set `publish=1` to `transfers.txt`. But, check from `outputdatasets.startswith('/FakeDataset` is better.
Nice. Thanks Stefano.

2023-07-20 05:49 UTC, novicecpp commented on src/python/ASO/Rucio/Transfer.py
> +            # break the loop and use first transfers.txt in case there is no
From what I understand
- We have all output files info to transfer (jobreport + logfile) before postjob execute.
- One Postjob.py process can execute [run()](https://github.com/dmwm/CRABServer/blob/2365939e2777e4afa2077f2c6b485b899c1facde/src/python/TaskWorker/Actions/PostJob.py#L519) at a time.
- [transfers.txt](https://github.com/dmwm/CRABServer/blob/2365939e2777e4afa2077f2c6b485b899c1facde/src/python/TaskWorker/Actions/PostJob.py#L983) get written by [for loop on output files](https://github.com/dmwm/CRABServer/blob/2365939e2777e4afa2077f2c6b485b899c1facde/src/python/TaskWorker/Actions/PostJob.py#L634).

I agree that it is hard to understand and no need to super optimize the code here.

2023-07-20 08:35 UTC, belforte commented
> We can set publish=1 to transfers.txt

yes we can, but IIUC only when using Rucio. One day I will have to go through PostJob and document what it does :-(

2023-07-20 08:39 UTC, novicecpp commented
We do not use anywhere in FTS_Transfers.py but it is for Publisher to acquire the new files [(ref)](https://github.com/dmwm/CRABServer/blob/2365939e2777e4afa2077f2c6b485b899c1facde/src/python/Databases/FileTransfersDB/Oracle/FileTransfers/FileTransfers.py#L32).

2023-07-20 08:46 UTC, belforte approved these changes

2023-07-20 08:55 UTC, novicecpp commented
Change PR title to be more accurate with the changes.

2023-07-20 08:55 UTC, merged