spark pipeline for crab usage analytics
dmwm/CRABServer pull request #7837
Opened 2023-08-17 14:50 UTC by ekongat

merge into dmwm/CRABServer the content of https://github.com/ekongat/crab-datapipeline , which aims at addressing the questions proposed in the Summer Student project [1].

Documentation on how to use this code is available in the crab docs [2]. 

Follow-up to this PR will be addressed by Dario and Wa in https://github.com/dmwm/CRABServer/issues/7798

---

[1] https://codimd.web.cern.ch/n0zKtr4KTZq2gquFpoQJdA?view
[2] https://cmscrab.docs.cern.ch/technical/crab-monitoring/crab-spark.html

2023-08-17 15:24 UTC, belforte requested changes
Since this just adds new files, there is no problem in merging. Any issue will be rectified later.
One thing you should change now is to avoid two files with same `osearch.py` name. If it is same file, put only one instance.
I like the organization but suggest to rename `crab_cronjobs` to `cronjobs` and `crab_manual` to `notebooks` or `examples`

2023-08-18 07:31 UTC, belforte commented
thanks I am happy with those changes

2023-08-18 07:31 UTC, belforte approved these changes

2023-08-18 17:52 UTC, mapellidario approved these changes
Thank you Ek-Ong! 
And thanks Stefano for having a look!

Everything looks good and we can merge this.

I have enabled the cronjob on crab-dev-tw04 for tomorrow morning at 5am, let's see how it goes :)

2023-08-18 17:53 UTC, merged