Taperecall: allow to recall any data tier if size less than threshold
dmwm/CRABServer pull request #7862
Opened 2023-09-01 15:20 UTC by novicecpp

Fix https://github.com/dmwm/CRABServer/issues/7841

The current policy is (correct me if I am wrong):
1. Allow to recall any dataset with size less than threshold.
2. If recall dataset are in `*AOD*` tier allow recall any size.

Thanks to Stefano for refactoring tape recall condition (especially the part involve `usePartialDataset`). It is much more easier to change the code.

This PR is special. Actually, the [first commit](https://github.com/dmwm/CRABServer/commit/e0dcafa7a88cbcdd066e5424f17b2c9e7919ba5a) is already do the job. But I want to show a small but valuable use case of unittest that helps me code with fewer mistakes and get faster feedback (no need to submit the tasks).

2023-09-01 20:15 UTC, belforte requested changes
thanks. It looks good. I am amazed how you found such a simple solution in the first commit !
And I like the way you separted the building of the msg which was the part which was giving me the hardest time, with that thing build incrementally that needs to be passed around.

The only thing, it looks like we never say:
this dataset is too large, if you can do with only a piece, use an inputBlocks list

It may be good to take this change to replace the ptr to sending a mail to dataops with a note to open a JIRA issues, which is what they prefer. Or we can do this after this is merged, as you like more.

2023-09-04 18:13 UTC, novicecpp commented
Changing the messages as Stefano suggested:

For input **block** larger than threshold (line 484):
```
Warning:                        Some blocks are on TAPE only and will not be processed.
                                The 'Data.inputBlocks' size is larger than the allowed size to issue automatic recall from TAPE (172.541TB/50TB).
                                If you need these blocks, contact Data Transfer team via https://its.cern.ch/jira/browse/CMSTRANSF
```
For input **dataset** larger than threshold (last else):
```
Warning:                        Some blocks are on TAPE only and will not be processed.
                                This dataset is too large for automatic recall from TAPE. If you can do with only a piece, use Data.inputBlocks configuration.
                                If you need the full dataset, contact Data Transfer team via https://its.cern.ch/jira/browse/CMSTRANSF
```

2023-09-05 08:27 UTC, belforte commented
looks good, thanks !

2023-09-05 08:28 UTC, belforte approved these changes

2023-09-05 09:18 UTC, merged