Clean up cmsbot's Rucio storage space
dmwm/CRABServer pull request #8327
Opened 2024-04-09 16:24 UTC by novicecpp

Hardcode username and filter for now, will fix when we migrate to Gitlab-CI later.

Jenkins job config: https://cmssdt.cern.ch/dmwm-jenkins/job/tseethon_Run/configure
Succesfully run: https://cmssdt.cern.ch/dmwm-jenkins/job/tseethon_Run/11/console

2024-04-09 16:27 UTC, mapellidario commented
Does it run on your environment if you use "env python3”? I would prefer to make clear that we really don't want to use py2 there :)

2024-04-09 16:30 UTC, novicecpp commented
I confused with this morning issue and look at wrong column on `rucio list-account-usage`,  thought the rucio space is insufficient and tried to fix immediately.
However, it not the case, everything is fine. For 6 months, we use only 60/100GB :-)

Anyhow, it is better to have cleanup and the scripts is ready to use.

2024-04-09 16:31 UTC, novicecpp commented
Sorry @mapellidario, I do not understand your question. What does `env python3` do?

2024-04-09 16:35 UTC, belforte commented
this will fail on EL9
```
#!/usr/bin/env python
```
there is no `python` there. Of course it does not matter if you start it with `python3 filename.py`. But why the shebang then ?

2024-04-09 16:43 UTC, belforte requested changes
see comments

2024-04-10 07:14 UTC, belforte commented on cicd/rucio/cleanup.py
> +DRY_RUN = os.getenv("DRY_RUN", 'True').lower() in ('True', 'true', '1', 't')
no need for 'True' since it is lowercase, right ?

2024-04-10 07:17 UTC, belforte commented on cicd/rucio/cleanup.py
> +    Delete rucio rules that older than 30 day. Make sure to delete only rules
rules THAT match

2024-04-10 07:24 UTC, belforte commented
looks good, I put two minor comments in code.
But I am still confused about the scope. It still looks to me that you only delete rules for transfer containers and not published dataset. There are also rules created by CRAB for final datasets which go to DBS (no `transfer` nor `Fake` in the name), no ?

Last note: why do you say that all test are gone ? Do you mean the rules, or the data ? I may be confused, but I thought we write to T2_CH_CERN which has lazy cleanup, not greedy. So data files will stick around also when rule is gone. Indeed we can consider using `--purge-replicas` (that's the CLI option, I do not have the python arg. at my fingertips).

2024-04-11 12:11 UTC, novicecpp commented
> Last note: why do you say that all test are gone ? Do you mean the rules, or the data ? I may be confused, but I thought we write to T2_CH_CERN which has lazy cleanup, not greedy. So data files will stick around also when rule is gone. Indeed we can consider using --purge-replicas (that's the CLI option, I do not have the python arg. at my fingertips).

The rules and its files because I force `--purge-replicas` at [line 49](https://github.com/dmwm/CRABServer/blob/dc2407fe452c5aa357721e7fc1dd47a2ffe5ac1c/cicd/rucio/cleanup.py#L49-L49).

2024-04-11 12:15 UTC, belforte commented
Thanks. I misread the `if` :-(  sorry for noise.

2024-04-12 10:56 UTC, merged